"""
test_required_columns.py

Validate that the processed dashboard-ready CSV contains all required columns,
correct California balancing authorities, no negative demand values, and valid
stress index and review priority values.

Run with:
    pytest tests/test_required_columns.py -v

These tests use the data/processed/ files generated by the pipeline.
If those files don't exist, tests are skipped with an explanatory message.
"""

import os
import sys
import pytest
import pandas as pd

# Allow imports from src/ when running from the project root
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from validate_grid_data import CALIFORNIA_AUTHORITIES

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")
DASHBOARD_FILE = os.path.join(PROCESSED_DIR, "california_grid_dashboard_ready.csv")

REQUIRED_COLUMNS = [
    "balancing_authority",
    "local_time_pacific",
    "demand_mw",
    "demand_forecast_mw",
    "net_generation_mw",
    "total_interchange_mw",
    "stress_index",
    "review_priority",
    "peak_demand_mw",
]

VALID_PRIORITIES = {
    "High Review Priority",
    "Medium Review Priority",
    "Low Review Priority",
}


@pytest.fixture(scope="module")
def dashboard_df():
    if not os.path.exists(DASHBOARD_FILE):
        pytest.skip(
            f"Dashboard file not found: {DASHBOARD_FILE}\n"
            "Run the pipeline (src/ modules or notebooks/california_grid_analysis.ipynb) first."
        )
    return pd.read_csv(DASHBOARD_FILE)


def test_required_columns_exist(dashboard_df):
    """All nine required columns must be present in the dashboard-ready file."""
    missing = [c for c in REQUIRED_COLUMNS if c not in dashboard_df.columns]
    assert not missing, f"Missing required columns: {missing}"


def test_california_authorities_present(dashboard_df):
    """At least one California balancing authority (BANC/CISO/IID/LDWP/TIDC) must exist."""
    found = set(dashboard_df["balancing_authority"].unique())
    ca_found = [a for a in CALIFORNIA_AUTHORITIES if a in found]
    assert len(ca_found) > 0, (
        f"No California balancing authorities found. Got: {found}"
    )


def test_all_five_california_authorities_present(dashboard_df):
    """All five California balancing authorities should be present."""
    found = set(dashboard_df["balancing_authority"].unique())
    missing = [a for a in CALIFORNIA_AUTHORITIES if a not in found]
    assert not missing, f"Missing California authorities: {missing}"


def test_no_negative_demand_values(dashboard_df):
    """Demand (MW) must not be negative — negative demand is not a valid grid state."""
    neg_count = (dashboard_df["demand_mw"] < 0).sum()
    assert neg_count == 0, f"Found {neg_count} negative demand_mw values"


def test_stress_index_exists(dashboard_df):
    """stress_index column must be present."""
    assert "stress_index" in dashboard_df.columns, "stress_index column is missing"


def test_stress_index_in_valid_range(dashboard_df):
    """Stress index values must be between 0 and 100 (inclusive)."""
    valid = dashboard_df["stress_index"].dropna()
    assert (valid >= 0).all(), "stress_index contains values below 0"
    assert (valid <= 100).all(), "stress_index contains values above 100"


def test_review_priority_exists(dashboard_df):
    """review_priority column must be present."""
    assert "review_priority" in dashboard_df.columns, "review_priority column is missing"


def test_review_priority_valid_labels(dashboard_df):
    """review_priority must only contain the three defined priority labels."""
    found = set(dashboard_df["review_priority"].dropna().unique())
    unexpected = found - VALID_PRIORITIES
    assert not unexpected, f"Unexpected review_priority values: {unexpected}"


def test_high_priority_hours_exist(dashboard_df):
    """At least one High Review Priority hour should be present in the dataset."""
    high_count = (dashboard_df["review_priority"] == "High Review Priority").sum()
    assert high_count > 0, "No High Review Priority hours found — check stress index thresholds"


def test_dataset_row_count(dashboard_df):
    """Dashboard file should have a meaningful number of rows (>1,000)."""
    assert len(dashboard_df) > 1000, (
        f"Dashboard file has only {len(dashboard_df)} rows — expected > 1,000"
    )
